### ISSUE TITLE
Sublists aren't returned as separate nodes

### ISSUE THREAD

**Issue by itaisteinherz** [syntax-tree/unist-util-find-all-after#5]
When parsing a remark AST that contains list and nested sublists inside them, the sublists aren't returned as separate lists, unlike the behavior you would get by using `visit(ast, 'list', list => ...)`.
This might be caused by me not understanding how to properly use `unist-util-find-all-after`, and so I'd love to get some help.

For more context, see sindresorhus/awesome-lint#57.

**Comment by wooorm** [comment]
Thanks for this issue!

You‘re talking about parsing and that seems more something for remark. If parsing is broken, could you expand on what you’re saying above with an [astexplorer](https://astexplorer.net) example or something like that?

And if it is about find-all-after, could you provide more context?

(I understand that when things don’t work it’s frustrating, but please also value our time: I’m sure you did a bunch of research, and now it’s your job to convince us and help us figure it out, for more tips, see [this section in the contributing docs](https://github.com/syntax-tree/unist/blob/master/contributing.md#submitting-an-issue))

**Comment by ChristianMurphy** [comment]
@itaisteinherz sublists are also returned as list nodes, see https://astexplorer.net/#/gist/97a5be1733af5cd470f4d1b4f94f157b/09297c069ba0ddcc6583434382e6b204685b6062

The confusion here may be that `unist-util-find-all-after` looks in sibling nodes, in the case of a list the sub-list, the sub-list is inside the current node, not after it.

**Comment by itaisteinherz** [comment]
@wooorm This is an example AST for which I get the issue: https://astexplorer.net/#/gist/4dcf294700d142a9de0ac13c2782a851/cbd507f482517c7a053a34fb9c1f72ec36338ef7.

Anyways, I think @ChristianMurphy's comment cleared it up well for me.
Thanks to both of you for your help!
